apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: test
build:
  artifacts:
  - image: test-oidc
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests/*
