apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: test-oidc
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: test@example.com
      jwksUri: https://example.com/jwks.json
